# Generated by Django 3.0.3 on 2020-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('number_CM', models.FloatField(null=True)),
                ('number_TD', models.FloatField(null=True)),
                ('number_TP', models.FloatField(null=True)),
                ('coef', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=200, null=True)),
                ('time', models.CharField(choices=[('7h00-9h00', '7h00-9h00'), ('9h-11h', '9h-11h'), ('11h-13h', '11h-13h'), ('13h-15h', '13h-15h'), ('15h-17h', '15h-17h'), ('17h-19h', '17h-19h'), ('19h-21h', '19h-21h')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('capacity', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé')], default='Libre', max_length=200, null=True)),
                ('meeting_time', models.ManyToManyField(to='ressources.MeetingTime')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('courses', models.ManyToManyField(to='ressources.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='ressources.Instructor'),
        ),
    ]
