# Generated by Django 3.0.3 on 2020-07-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
