# Generated by Django 3.0.3 on 2020-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_auto_20200725_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=200, null=True, verbose_name='Code EC'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coef',
            field=models.FloatField(blank=True, null=True, verbose_name='Nombre crédits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='ressources.Instructor', verbose_name='Enseignants'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_CM',
            field=models.FloatField(null=True, verbose_name='Nombre heures CM'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_TD',
            field=models.FloatField(null=True, verbose_name='Nombre heures TD'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_TP',
            field=models.FloatField(null=True, verbose_name='Nombre heures TP'),
        ),
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='ressources.Course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='department',
            name='size',
            field=models.FloatField(null=True, verbose_name='Effectif'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=200, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=200, null=True, verbose_name='Jour'),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('7h-9h', '7h-9h'), ('9h-11h', '9h-11h'), ('11h-13h', '11h-13h'), ('13h-15h', '13h-15h'), ('15h-17h', '15h-17h'), ('17h-19h', '17h-19h'), ('19h-21h', '19h-21h')], max_length=200, null=True, verbose_name='Plage horaire'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.FloatField(null=True, verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='room',
            name='meeting_time',
            field=models.ManyToManyField(to='ressources.MeetingTime', verbose_name='Plages horaires'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé')], default='Libre', max_length=200, null=True, verbose_name='Etat'),
        ),
    ]
