# Generated by Django 3.0.3 on 2020-09-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_meetingtime_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nom du département')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], default='Semestre 1', max_length=200, null=True, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Faculty', verbose_name='Departement'),
        ),
    ]
