# Generated by Django 3.0.3 on 2020-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0007_auto_20200909_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.FloatField(null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], default='Semestre 1', max_length=200, null=True, verbose_name='Semestre'),
        ),
    ]
