# Generated by Django 3.0.3 on 2020-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0008_auto_20200914_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('Niveau 1', 'Niveau 1'), ('Niveau 2', 'Niveau 2'), ('Niveau 3', 'Niveau 3'), ('Niveau 4', 'Niveau 4'), ('Niveau 5', 'Niveau 5')], default='Niveau 1', max_length=200, null=True, verbose_name='Niveau'),
        ),
    ]
