# Generated by Django 3.0.3 on 2020-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Désactivé', 'Désactivé'), ('En cours', 'En cours')], default='En_cours', max_length=200, null=True)),
            ],
        ),
    ]
