# Generated by Django 3.0.3 on 2020-07-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_auto_20200725_2112'),
        ('saisie', '0002_seance_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Course'),
        ),
        migrations.AddField(
            model_name='seance',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Department'),
        ),
        migrations.AddField(
            model_name='seance',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Instructor'),
        ),
        migrations.AddField(
            model_name='seance',
            name='meetingTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.MeetingTime'),
        ),
        migrations.AddField(
            model_name='seance',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Room'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='classes',
            field=models.ManyToManyField(to='saisie.Seance'),
        ),
    ]
