# Generated by Django 3.0.3 on 2020-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0003_auto_20200728_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Désactivé', 'Désactivé'), ('En cours', 'En cours')], default='En cours', max_length=200, null=True),
        ),
    ]
