# Generated by Django 3.0.3 on 2020-07-31 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_auto_20200731_1630'),
        ('saisie', '0004_auto_20200729_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Department', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='Effectif'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Department', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Instructor', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='meetingTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.MeetingTime', verbose_name='Plage horaire'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Room', verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
