# Generated by Django 3.0.3 on 2020-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0008_auto_20200831_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AlterField(
            model_name='seance',
            name='activity',
            field=models.CharField(blank=True, choices=[('Cours Magistral', 'Cours Magistral'), ('Travaux Dirigés', 'Travaux Dirigés'), ('Travaux Pratiques', 'Travaux Pratiques'), ('Contrôle Continu', 'Contrôle Continu'), ('Examens', 'Examens'), ('Soutenances', 'Soutenances'), ('Autre', 'Autre')], default='Cours Magistral', max_length=200, null=True, verbose_name='Activité'),
        ),
    ]
