# Generated by Django 3.0.3 on 2020-09-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0011_header_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='level',
        ),
        migrations.AddField(
            model_name='header',
            name='levels',
            field=models.ManyToManyField(to='saisie.Level', verbose_name='Niveaux'),
        ),
        migrations.AlterField(
            model_name='header',
            name='semester',
            field=models.CharField(blank=True, choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2')], default='Semestre 1', max_length=200, null=True, verbose_name='Semestre'),
        ),
    ]
