# Generated by Django 3.0.3 on 2020-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saisie', '0012_auto_20200921_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du groupe'),
        ),
    ]
